# Site settings
title: 天道酬勤-立即行动
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "张欢|读而立·写而生"
baseurl: ""
url: "http://zhanghuanhome"

# About/contact
owner: 
  name: " ZhagnHuan"
  email: TheBlueSky123@gmail.com
  bio: "天道酬勤，皆有可能"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  cnfeat
twitter_username: feat
github_username: cnfeat
facebook_username: 
weibo_username: cnfeat 
zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CnFeat"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : cnfeat
  disqus :
      short_name : cnfeat

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
theme: jekyll-theme-merlot
